version: '3.9'

services:
  go_api_mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: go_api_mysql
    ports:
      - "3306:3306"
    volumes:
        - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: go_api
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci