version: '3.9'

services:
  go_api_mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: go_api_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: go_api
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      TZ: "Asia/Tokyo"